### ISSUE TITLE
Invalid agg type in client

### ISSUE THREAD

**Issue by bigsheeper** [zilliztech/arctern#515]
- Pandas aggregation dose not support UNIQUE type, so it's invalid, should be removed.
- We support COUNT aggregation type now, so I suggest to add COUNT, which in requests paramters is 'count'
- AVG aggregation in pandas is 'mean'
- STDDIV aggregation in pandas is 'std'

**Comment by talentAN** [comment]
> * Pandas aggregation dose not support UNIQUE type, so it's invalid, should be removed.
> * We support COUNT aggregation type now, so I suggest to add COUNT, which in requests paramters is 'count'
> * AVG aggregation in pandas is 'mean'
> * STDDIV aggregation in pandas is 'std'

pls give me some example sqls ,thx~

**Comment by bigsheeper** [comment]
**1. This request should be removed:**
```json
{"id":"4f7d50ee7fd811eab4e204d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi","type":"heat","params":{"width":693,"height":1107,"heat":{"bounding_box":[-74.01556543545699,40.69354738164881,-73.9434424136598,40.780921656427836],"coordinate_system":"EPSG:4326","map_zoom_level":12.72196098443694,"aggregation_type":"unique"}}}}
```
**2. This request:**
```
{"id":"4f7d50ee7fd811eab4e204d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi","type":"heat","params":{"width":693,"height":1107,"heat":{"bounding_box":[-74.01556543545699,40.69354738164881,-73.9434424136598,40.780921656427836],"coordinate_system":"EPSG:4326","map_zoom_level":12.72196098443694,"aggregation_type":"count"}}}}
```
should be added.

**3. This request:**
```
{"id":"4f7d50ee7fd811eab4e204d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi","type":"heat","params":{"width":693,"height":1107,"heat":{"bounding_box":[-74.01556543545699,40.69354738164881,-73.9434424136598,40.780921656427836],"coordinate_system":"EPSG:4326","map_zoom_level":12.72196098443694,"aggregation_type":"avg"}}}}
```
should be modified to:
```
{"id":"4f7d50ee7fd811eab4e204d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi","type":"heat","params":{"width":693,"height":1107,"heat":{"bounding_box":[-74.01556543545699,40.69354738164881,-73.9434424136598,40.780921656427836],"coordinate_system":"EPSG:4326","map_zoom_level":12.72196098443694,"aggregation_type":"mean"}}}}
```
**4. This request:**
```
{"id":"4f7d50ee7fd811eab4e204d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi","type":"heat","params":{"width":693,"height":1107,"heat":{"bounding_box":[-74.01556543545699,40.69354738164881,-73.9434424136598,40.780921656427836],"coordinate_system":"EPSG:4326","map_zoom_level":12.72196098443694,"aggregation_type":"stddiv"}}}}
```
should be modified to:
```
{"id":"4f7d50ee7fd811eab4e204d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi","type":"heat","params":{"width":693,"height":1107,"heat":{"bounding_box":[-74.01556543545699,40.69354738164881,-73.9434424136598,40.780921656427836],"coordinate_system":"EPSG:4326","map_zoom_level":12.72196098443694,"aggregation_type":"std"}}}}
```

**as well as in the weighted pointmap and choroplethmap**

**Comment by talentAN** [comment]
mean and count works well , std return empty picture
![image](https://user-images.githubusercontent.com/17634030/79710682-5652f900-82f8-11ea-87b6-845d88beb081.png)


{"id":"c00ff8c482ae11ea9e3404d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-74.02987975875563 40.70717922506145, -74.02987975875563 40.80718202380825, -73.91430446843016 40.80718202380825, -73.91430446843016 40.70717922506145, -74.02987975875563 40.70717922506145))')))","type":"heat","params":{"width":998,"height":1139,"heat":{"bounding_box":[-74.02987975875563,40.70717922506145,-73.91430446843016,40.80718202380825],"coordinate_system":"EPSG:4326","map_zoom_level":12.567844209918487,"aggregation_type":"max"}}}}

**Comment by talentAN** [comment]
choropleth render error, pls check

{
  "id": "c00ff8c482ae11ea9e3404d4c4a9870c",
  "query": {
    "sql": "SELECT total_amount AS w, ST_GeomFromText(buildingtext_dropoff) AS wkt FROM nyc_taxi WHERE (buildingtext_dropoff!='') AND (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-74.01211730772279 40.744131574432316, -74.01211730772279 40.772392718287136, -73.95452788712015 40.772392718287136, -73.95452788712015 40.744131574432316, -74.01211730772279 40.744131574432316))')))",
    "type": "choropleth",
    "params": {
      "width": 514,
      "height": 332,
      "choropleth": {
        "bounding_box": [
          -74.01211730772279,
          40.744131574432316,
          -73.95452788712015,
          40.772392718287136
        ],
        "coordinate_system": "EPSG:4326",
        "color_gradient": ["#115f9a", "#d0f400"],
        "color_bound": [2.5, 110],
        "opacity": 1,
        "aggregation_type": "mean"
      }
    }
  }
}

{"code":-1,"message":"An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.\n: org.apache.spark.SparkException: Job aborted due to stage failure: Task 10 in stage 1653.0 failed 1 times, most recent failure: Lost task 10.0 in stage 1653.0 (TID 25982, infini, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 597, in main\n    process()\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 589, in process\n    serializer.dump_stream(out_iter, outfile)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/serializers.py\", line 398, in dump_stream\n    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/serializers.py\", line 234, in dump_stream\n    for batch in iterator:\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/serializers.py\", line 391, in init_stream_yield_batches\n    for series in iterator:\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 442, in mapper\n    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 442, in <genexpr>\n    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 106, in <lambda>\n    return lambda *a: (verify_result_length(\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 102, in verify_result_length\n    raise RuntimeError(\"Result vector from pandas_udf was not the required length: \"\nRuntimeError: Result vector from pandas_udf was not the required length: expected 3261, got 0\n\n\tat org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:484)\n\tat org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:99)\n\tat org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:49)\n\tat org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:437)\n\tat org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)\n\tat org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)\n\tat org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)\n\tat org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:726)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)\n\tat org.apache.spark.sql.execution.python.BatchIterator.hasNext(ArrowEvalPythonExec.scala:39)\n\tat org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.$anonfun$writeIteratorToStream$1(ArrowPythonRunner.scala:86)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)\n\tat org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)\n\tat org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.writeIteratorToStream(ArrowPythonRunner.scala:101)\n\tat org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:373)\n\tat org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1932)\n\tat org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:213)\n\nDriver stacktrace:\n\tat org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:1989)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1977)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1976)\n\tat scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)\n\tat scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1976)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:956)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:956)\n\tat scala.Option.foreach(Option.scala:407)\n\tat org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:956)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2206)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2155)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2144)\n\tat org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:758)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2116)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2137)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2156)\n\tat org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:154)\n\tat org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)\n\tat sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 597, in main\n    process()\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 589, in process\n    serializer.dump_stream(out_iter, outfile)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/serializers.py\", line 398, in dump_stream\n    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/serializers.py\", line 234, in dump_stream\n    for batch in iterator:\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/serializers.py\", line 391, in init_stream_yield_batches\n    for series in iterator:\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 442, in mapper\n    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 442, in <genexpr>\n    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 106, in <lambda>\n    return lambda *a: (verify_result_length(\n  File \"/home/sheep/miniconda3/envs/arctern/lib/python3.8/site-packages/pyspark-3.0.0.dev2-py3.8.egg/pyspark/python/lib/pyspark.zip/pyspark/worker.py\", line 102, in verify_result_length\n    raise RuntimeError(\"Result vector from pandas_udf was not the required length: \"\nRuntimeError: Result vector from pandas_udf was not the required length: expected 3261, got 0\n\n\tat org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:484)\n\tat org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:99)\n\tat org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:49)\n\tat org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:437)\n\tat org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)\n\tat org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)\n\tat org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)\n\tat org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:726)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)\n\tat org.apache.spark.sql.execution.python.BatchIterator.hasNext(ArrowEvalPythonExec.scala:39)\n\tat org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.$anonfun$writeIteratorToStream$1(ArrowPythonRunner.scala:86)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)\n\tat org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)\n\tat org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.writeIteratorToStream(ArrowPythonRunner.scala:101)\n\tat org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:373)\n\tat org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1932)\n\tat org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:213)\n","status":"error"}

**Comment by bigsheeper** [comment]
For the choroplethmap error, The order of inputs from sql is **very** important. Server uses the first column as wkt, uses the second column as count by default. Column name is various, server never knows which column is wkt, which column is count, so please keep the order of inputs. 

So, `total_amount AS w, ST_GeomFromText(buildingtext_dropoff) AS wkt,`, should be `ST_GeomFromText(buildingtext_dropoff) AS wkt, total_amount AS w`.

**Comment by bigsheeper** [comment]
For the std error:
It works well in the newest arctern:
![heatmap](https://user-images.githubusercontent.com/42060877/79744251-9c2fb180-8338-11ea-8177-5a7f25ef6964.png)
